dubbo:
  application:
    name: ${spring.application.name}
    owner: rookiefly
  protocol:
    port: 20880
    name: dubbo
  scan:
    basePackages: com.rookiefly.open.dubbo.monitor.service
logging:
  level:
    root: info
management:
  endpoint:
    dubbo:
      enabled: true
    dubboConfigs:
      enabled: true
    dubboProperties:
      enabled: true
    dubboReferences:
      enabled: true
    dubboServices:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
mybatis:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mappers/*Mapper.xml
  type-aliases-package: com.rookiefly.open.dubbo.monitor.domain
spring:
  profiles:
    active: @spring.active@
  main:
    allow-bean-definition-overriding: true
  application:
    name: dubbo-monitor-plus
  jetbrick:
    template:
      charset: UTF-8
      config:
        jetx:
          autoscan:
            packages: com.rookiefly.open.dubbo.monitor.support
          import:
            methods: com.rookiefly.open.dubbo.monitor.support.StringMethods
      enabled: true
      prefix: templates/
      suffix: .html